# 基础配置
CONFIG_MAIN_STACK_SIZE=4096

CONFIG_REBOOT=y
CONFIG_PICOLIBC=y

# 启用 SPI 总线硬件驱动
CONFIG_SPI=y

# 启用核心显示子系统与 MIPI DBI 框架
CONFIG_DISPLAY=y
CONFIG_MIPI_DBI=y

# CONFIG_DMA=y
# CONFIG_SPI_ASYNC=y
# CONFIG_SPI_PL022_DMA=y
# CONFIG_DMA_RPI_PICO=y

# 如果需要绘制文字和图形，建议启用图形库
# CONFIG_LVGL=y
# CONFIG_LV_COLOR_DEPTH_1=y

# CONFIG_LV_USE_THEME_DEFAULT=n
# CONFIG_LV_USE_THEME_MONO=y

# CONFIG_LV_Z_BITS_PER_PIXEL=1
# CONFIG_LV_Z_VDB_SIZE=100
# CONFIG_LV_Z_FULL_REFRESH=y
# CONFIG_LV_FONT_MONTSERRAT_14=y
# CONFIG_LV_Z_MEM_POOL_SIZE=16384

# CONFIG_LV_USE_LABEL=y
# CONFIG_LV_USE_LINE=y
# CONFIG_LV_USE_CALENDAR=n
# CONFIG_LV_USE_DROPDOWN=n

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y
CONFIG_UART_LINE_CTRL=y
CONFIG_USB_DEVICE_PRODUCT="RP2040 Console"
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y


CONFIG_HEAP_MEM_POOL_SIZE=10000

# Force the Display subsystem to output granular debug data
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
# 2. 将全局默认日志级别提升至 DEBUG 级别
CONFIG_LOG_MAX_LEVEL=4

# 3. 如果使用的是 MIPI-DBI 桥接驱动或显示子系统，单独解锁该模块的 DEBUG 级别
CONFIG_DISPLAY_LOG_LEVEL_DBG=y
CONFIG_DISPLAY_LOG_LEVEL_ERR=y
CONFIG_MIPI_DBI_LOG_LEVEL_DBG=y

# CONFIG_SPI_LOG_LEVEL_DBG=y
CONFIG_DMA_LOG_LEVEL_INF=y